### ISSUE TITLE
How to change the name of the panel from SkyVector to another name?

### ISSUE THREAD

**Issue by mariocmg** [bymaximus/msfs2020-toolbar-window-template#1]
How to change the name of the panel from SkyVector to another name?

**Comment by bymaximus** [comment]
You need to change it at `msfs2020-toolbar-window-template/fs-base-ingamepanels-custom/Build/PackageSources/fs-base-ingamepanels-custom.xml` and then recompile

**Comment by mariocmg** [comment]
![image](https://user-images.githubusercontent.com/38396612/95083764-3d5ec880-071d-11eb-986d-09ae694b6899.png)
I have change the name, but in the game you don't see

**Comment by bymaximus** [comment]
Did you recompiled to generate the new SPB?

**Comment by mariocmg** [comment]
No, How it is do it?

**Comment by bymaximus** [comment]
Its in the README.md

#
To build the SPB if you have changed UI panel template definition

SDK\Tools\bin\fspackagetool.exe fs-base-ingamepanels-custom\Build\fs-base-ingamepanels-custom.xml -nomirroring

It will generate the SPB at fs-base-ingamepanels-custom\Build\Packages\fs-base-ingamepanels-custom\Build copy the SPB to fs-base-ingamepanels-custom\InGamePanels.

Copy the package to community folder BUT DO NOT COPY the fs-base-ingamepanels-custom\Build directory.
