### ISSUE TITLE
No audio-passthrough using <audio> html5 tag

### ISSUE THREAD

**Issue by bogdanrau** [bymaximus/msfs2020-toolbar-window-template#13]
I've been working on a radio toolbar item to play local radio stations depending on an aircraft's location. The app sits remotely on a server, and is loaded as a website in an iframe. While I can get the site to load, and the functionality to pick up radio stations works, I cannot get the audio stream to load. I am making the assumption that the audio stream (<audio> object) never loads in the DOM, though I have no idea where to look to see if that's the case.

Any thoughts on whether this is a hickup, or an actual limitation? Any way I can tell what ends up getting loaded? For reference, I have embedded this in an iframe outside of the sim, and things work as expected.

![radio](https://user-images.githubusercontent.com/7134642/105895257-27299080-5fca-11eb-87e5-1d63df547721.png)

**Comment by bymaximus** [comment]
Its probably because the coherent browser engine msfs is using does not support the tag/object you trying to use, it for example does not load PDF.
