### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by tuxuera** [bymaximus/msfs2020-toolbar-window-template#15]
Hi maxymus excellent work you have done.i wanted to ask if there is a way to have more toolbar-window  say two or three more and so they would enter other websites, thank you very much for everything.

**Comment by bergziege** [comment]
You might have a look at https://github.com/bergziege/MSFS-Toolbar-Generator
Its still more like a beta version ... but should work to generate multiple toolbar templates
If you have any questions about it, please use issues or discussion over there.
