### ISSUE TITLE
I don't get the SkyVector program.

### ISSUE THREAD

**Issue by A-Sot** [bymaximus/msfs2020-toolbar-window-template#20]
First, thank you very much for your input.

I wanted to ask you what I do next when I get the api and ipfy screenshoot, the last screen that you have?

THANKS YOU

**Comment by Ronnet66** [comment]
Stuck at the same point, duh

**Comment by bymaximus** [comment]
https://github.com/bymaximus/msfs2020-toolbar-window-template/issues/10#issuecomment-758611820

Skyvector disabled embedding their site through an iframe.

**Comment by javadmisa67** [comment]
why

**Comment by bymaximus** [comment]
> why

You need to ask them.



> First, thank you very much for your input.
> 
> I wanted to ask you what I do next when I get the api and ipfy screenshoot, the last screen that you have?
> 
> THANKS YOU

This is a TEMPLATE, you can use this if you are a developer. This is not for final customer/consumer.

**Comment by javadmisa67** [comment]
Hello . Thank you for your response. I'm not a developer, but I'm
interested in creating a toolbar that I can search on various websites
Is it possible to create such a toolbar and send it to me? Or make an
instructional video about making a toolbar for the simulator and give it to
me



در تاریخ پنجشنبه ۳ فوریهٔ ۲۰۲۲،‏ ۴:۲۱ bymaximus ***@***.***>
نوشت:
