### ISSUE TITLE
Blurry?

### ISSUE THREAD

**Issue by Wibbbs** [bymaximus/msfs2020-toolbar-window-template#3]
This works ok but definitely has some hiccups. Some buttons on sky vector don't seem to work. I also noticed that resolution is a lot more blurry in the panel than if I load skyvector in a proper browser. 

Not sure if anything can be done about any of these, just thought I would start the conversation.

Also is there any documentation surrounding this? I would love to play around with this as well but there doesn't seem to be any documentation for UI modifications using the SDK.

**Comment by bymaximus** [comment]
Hello, the UI system MSFS2020 uses is the coherent UI, its based on chromium browser engine (a modified version I guess), it does not support all features a normal today´s  webbrowser has. For example, I dont think is possible to load and display embedded PDF files.

I think that´s why SkyVector doesnt fully work, I created it loading SkyVector just to show it as an example.

There is not SDK documentation for UI currently, asobo will release later I guess, not sure if they will allow make changes to the UI using the SDK.

**Comment by bymaximus** [comment]
Ops...
![chart](https://user-images.githubusercontent.com/595991/95541103-dc5b1d00-09c8-11eb-9a10-fd57430b60fc.png)

**Comment by Sub-7** [comment]
Ops...???
we can't do anything with it, please show us the code with .pdf example.

**Comment by bymaximus** [comment]
Is not .pdf, the engine fs ui uses doesnt support embeded pdf objects, I will commit when I finish.
