### ISSUE TITLE
change url

### ISSUE THREAD

**Issue by novamix** [bymaximus/msfs2020-toolbar-window-template#4]
Hello, it is a great plugin, but to change the url to show only do I have to modify the js?

The first time I modified it and it worked, but now I don't get it .. I don't know if I should modify any more files?

Also since there is no documentation about the SVG what format it should have since I can't show my SVG, it appears transparent.

Sorry for my English as a translator.

thanks.

**Comment by bymaximus** [comment]
Sorry, I dont understand what you mean about the 'change the url to show'?!

About SVG, I think the required code is this part bellow, plus you must set the 'icon' name in the SVG and use same name in the source, did you recompile the SPB with the new SVG?
```
<svg id="Titre" xmlns="http://www.w3.org/2000/svg" width="64.000000px" height="64.000000px" viewBox="0 0 384.000000 384.000000">
  <title>ICON_TOOLBAR_SKYVECTOR</title> <============ ICON NAME
  <g id="HIGHLIGHT">
```
The viewBox size will be according with your original SVG.
``` viewBox="0 0 384.000000 384.000000"```

You can look at the original packages folder the folder 'fs-base-ingamepanels' which contains all those UI windows to have some better idea how it works.

**Comment by Yngwiedis** [comment]
I think he ask if he can change the URL who open in the window.
He want to open another site except skyvector.

**Comment by bymaximus** [comment]
You can change the URL at code or even create a textfield to put the URL you want to load. This package is just a template so other coders can easy start a new custom toolbar window.

**Comment by MultiMediaWIll** [comment]
> You can change the URL at code or even create a textfield to put the URL you want to load. This package is just a template so other coders can easy start a new custom toolbar window.

Is there a way to make this work with navigraph charts? I changed the files to target "https://charts.navigraph.com/" but when I click sign in on the window in game, Navigraph says "Navigraph Charts requires an active internet connection" despite being connected to the internet.

**Comment by bymaximus** [comment]
No.
