### ISSUE TITLE
Help with msfs2020-toolbar-window-template

### ISSUE THREAD

**Issue by ThunderRod7** [bymaximus/msfs2020-toolbar-window-template#5]
Ok I installed it into "Community" and it is not working or showing up on my toolbar. I did notice in your download page it says to just download in your "Community" and your all good to go? but then I noticed down further about doing things to get it going as to which I have no clue as to weather or not I have to do that, as I am not tech savoy at all and I am an old guy which loves SkyVector and I normally use it with an open webpage but this is a great idea; but I would love to have it work for me. PLEASE HELP this old fella to KNOW WHAT TO DO :-) Many Thanks

**Comment by bymaximus** [comment]
Copy the package `fs-base-ingamepanels-custom` folder to community folder.

**Comment by kaptajnjensen** [comment]
> Copy the package `fs-base-ingamepanels-custom` folder to community folder.

Where is that "package"???

**Comment by bymaximus** [comment]
![image](https://user-images.githubusercontent.com/595991/95664480-90ba8780-0b1e-11eb-9cfa-dfef40111391.png)
