### ISSUE TITLE
Difficulty Signing In To My Skyvector account

### ISSUE THREAD

**Issue by kaptajnjensen** [bymaximus/msfs2020-toolbar-window-template#6]
I have installed Skyvector but have run into a snag.
The MSFS keyboard assignments makes it impossible to sign in to my Skyvector account.
For example, typing the letter v opens the map and letter c opens the checklist.
Is there any way to overcome this, so I can use your template?

**Comment by bymaximus** [comment]
Im not sure, probably yes since you can type in other windows. I will check when I have time.

**Comment by bymaximus** [comment]
SkyVector is now not allowing be loaded from iframe.
