### ISSUE TITLE
Feature request: Read/write flightsim data from the toolbar app?

### ISSUE THREAD

**Issue by scelts** [bymaximus/msfs2020-toolbar-window-template#7]
Is this at all possible, or one still needs some external simconnect client?

**Comment by bymaximus** [comment]
Yes, its possible.

**Comment by scelts** [comment]
Can you give me some more info if you know? I see that you included bunch of these files from the MSFS folders:

```
<script type="text/javascript" src="/JS/dataStorage.js"></script>
<script type="text/javascript" src="/JS/buttons.js"></script>
<script type="text/javascript" src="/JS/Services/ToolBarPanels.js"></script>
```

But unfortunately thanks to Microsoft, I can't open them in the WindowsApps folder, to check what's there to use (tried with the ownership change, it specifically prohibits the MS apps).
Is there any easier way to get the info what you have there to use, besides to booting in Linux and see the files?
