### ISSUE TITLE
Empty window on open

### ISSUE THREAD

**Issue by TrickShotMLG02** [bymaximus/msfs2020-toolbar-window-template#8]
Everything worked fine, but after the latest update it only shows an empty window after opening it from the toolbar

**Comment by a300600st** [comment]
Same problem here.

**Comment by flymypi** [comment]
It seems like Skyvector does not allow iframes anymore. At least that's what I think after this simple code failed:
`<iframe src="https://skyvector.com/"></iframe>`

**Comment by vmoins7212** [comment]
Same problem here. Do you plan to look for a fix ? I've tested with another toolbar, the one related to little navmap, there is also a git project which offers an add-on under the form of a toolbar button which shows a map. The window is empty over there too.
@flymypi talked about iFrames... I'm wondering if this is not related to "enable iframes" in the internet browser's option... 
Another option is define your default internet browser to another one, like Opera, which by default enables iFrames. Edge, Chrome and Firefox do not.

**Comment by flymypi** [comment]
@vmoins7212 MSFS does not make use of any browser you have installed externally. It ships with a rudimentary internal one. As a hoster, you can however restrict other's from embedding your site in form of iframes, which I suspect SkyVector have done.

I was able to get this template to work using my own website.

**Comment by bymaximus** [comment]
Exactly, the msfs “browser” engine is simple and doesnt contains all features a normal browser have. I dont have access to msfs right now to check for fixes

**Comment by bakkerj1980** [comment]
Hi, any news about this issue? I really want to use this mod to load skyvector while flying in VR. But the popup window still only shows empty grey content. Hope this can be fixed or worked around.

Thanks!

**Comment by bymaximus** [comment]
Seems SkyVector now is not allowing their website be loaded from iframes. I changed the template to load other website.
