### ISSUE TITLE
What are the requirements for the SVG icon

### ISSUE THREAD

**Issue by bergziege** [bymaximus/msfs2020-toolbar-window-template#9]
As soon as I change the svg icon it goes blank in the sim.

Example:
- Using Inkscape to open ICON_TOOLBAR_*.svg
- replacing the skyvector symbol with some custom text and drawing (b/w only)
- click save (so I did not change any metadata, did I?)

-> gives me a blank icon in the sim.

So what requirements does the svg have to be shown in the sim like the skyvector one?

**Comment by bymaximus** [comment]
1. Does the new Icon shows up in the browser (firefox/chrome/etc)? 
2. Did you recompiled the SPB?

**Comment by bergziege** [comment]
Got it working. But currently not exactly sure what solved it:

- Had text as a text object not as a path -> converted text to path
- Cleaned it by hand to match the scyvector.svg example.

Think Inkscape detroyed the structure/I deleted too much. In my svg the <g HIGHLIGHT and the <g fill ... tags were missing.
